/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as RunsRunIdReviewRouteImport } from './routes/runs/$runId.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdReviewRoute = RunsRunIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => RunsRunIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/$runId/review': typeof RunsRunIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/$runId/review': typeof RunsRunIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/$runId/review': typeof RunsRunIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/runs/$runId' | '/runs/$runId/review'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/runs/$runId' | '/runs/$runId/review'
  id: '__root__' | '/' | '/runs/$runId' | '/runs/$runId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunsRunIdRoute: typeof RunsRunIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId/review': {
      id: '/runs/$runId/review'
      path: '/review'
      fullPath: '/runs/$runId/review'
      preLoaderRoute: typeof RunsRunIdReviewRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
  }
}

interface RunsRunIdRouteChildren {
  RunsRunIdReviewRoute: typeof RunsRunIdReviewRoute
}

const RunsRunIdRouteChildren: RunsRunIdRouteChildren = {
  RunsRunIdReviewRoute: RunsRunIdReviewRoute,
}

const RunsRunIdRouteWithChildren = RunsRunIdRoute._addFileChildren(
  RunsRunIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunsRunIdRoute: RunsRunIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
